const express = require('express');
const router = express.Router();
const CommentController = require('../Controllers/comment');
const auth = require('../middleware/authentication');
router.get('/getCommentById/:id',CommentController.getCommentById);
router.get('/getRepliesByCommentId/:id',CommentController.getRepliesByCommentId);
router.post('/addComment',auth,CommentController.addComment);
router.post('/addReply/:commentId',auth,CommentController.addReply);
router.get('/getCommentByVideoId/:videoId',CommentController.getCommentByVideoId);
router.put('/toggleCommentLikeDislike/:id',auth,CommentController.toggleCommentLikeDislike);
module.exports = router;